### ISSUE TITLE
Add support for Data Table rendering

### ISSUE THREAD

**Issue by shah** [cmoog/vscode-sql-notebook#10]
@cmoog it would be great to add support for [Data Table](https://github.com/RandomFractals/vscode-data-table) renderer. Your extension is great as it is but could be enhanced with `Data Table`.

**Comment by cmoog** [comment]
Oh nice find, that would certainly be an improvement over our current table rendering.

**Comment by miguel-vivanco** [comment]
@cmoog it is a very usefull extension, It is possible to dissable the autowrap the values?, beacause the row height increase a lot for fields with long string value.

**Comment by cmoog** [comment]
@miguel-vivanco I do agree that the autowrap behavior is frustrating at the moment. Rather than exposing configurations for each aesthetic deficiency individually, I'd rather solve the table rendering problem holistically with something akin to the [Data Table](https://github.com/RandomFractals/vscode-data-table) approach.

**Comment by RandomFractals** [comment]
@shah thanks for mentioning my data table renderers. 

@cmoog I really like your SQL notebook extension. It's probably the simplest implementation I've seen to run SQL queries in vscode notebooks.

My data table renderers attempt to parse CSV, JSON and GeoJSON data outputs based on the mime type as defined in this package.json: https://github.com/RandomFractals/vscode-data-table/blob/main/package.json#L87

```json
...
  "notebookRenderer": [
      {
        "id": "vscode-data-table",
        "entrypoint": "./out/renderer/dataTable.js",
        "displayName": "Data Table",
        "mimeTypes": [
          "application/json",
          "application/geo+json",
          "application/octet-stream",
          "application/vnd.code.notebook.stdout",
          "application/xml",
          "text/csv",
          "text/plain",
          "text/x-json",
          "text/xml"
        ]
      },
...```

So, if your output JSON or CSV data for the query results instead of using markdown tables with `text/markdown` mime type, your notebooks will display simple html data tables, data summary, or use flat data viewer depending on the `Change Presentation` selection for the cell.

You can also define a dependency on my `RandomFractalsInc.vscode-data-table` renderers extension in your extension package.json to ensure your SQL Notebook users can use or select them for rendering SQL Query restuls.
