### ISSUE TITLE
Persist session across cells

### ISSUE THREAD

**Issue by RedEyedDog** [cmoog/vscode-sql-notebook#30]
Hey

I'm having an issue where say if I create a temp table.. in the next cell its not accessible, I get the error:
 "Invalid object name '#temptable'. 

I think this is possible as the standard SQL Server plugin is able to do this across queries?

Thanks

**Comment by cmoog** [comment]
Currently, when you connect in the sidebar we create a new connection pool. Then, each cell execution corresponds to a new connection from that pool. This model allows you to execute two cells concurrently since they're running through different connections.

To persist sessions across cells in the way you're describing, I think we'd need to use the same connection. Can your use case be solved by executing the related queries in the same cell?
