### ISSUE TITLE
Date values presented as timestamps

### ISSUE THREAD

**Issue by lorefnon** [cmoog/vscode-sql-notebook#58]
Thank you for creating this extension - this is very useful. 

One oddity I discovered was that it presents date values as timestamps. 

![image](https://user-images.githubusercontent.com/1449492/194036544-4cbe11c2-74b6-4264-9461-28adfbdbe0bc.png)

In the database (postgres) the column is a date type column so it is confusing that a time component is also being shown here. 

Here is the same query result presented in another db interface (beekeeper) 

![image](https://user-images.githubusercontent.com/1449492/194036800-8d75892f-b0b1-4e70-999a-d90a44fb2ee4.png)

There is also some timezone conversion happening due to which the date does not match (my server is in US where as I am running the notebook in India).

**Comment by cmoog** [comment]
Thanks for this report. I suspect there is a way to discern timestamp vs. date in the types returned by each respected database driver but it may be tricky because JS only has one native `Date` type. Either way, we'll need to address this for each underlying driver implementation.

Will be a bit tedious but nothing difficult. Can likely be fixed by only editing https://github.com/cmoog/vscode-sql-notebook/blob/master/src/driver.ts. If someone wants to pick this up I'll make sure to review quickly and provide feedback / merge when ready.
