### ISSUE TITLE
How to specify SSL options?

### ISSUE THREAD

**Issue by ryan-efendy** [cmoog/vscode-sql-notebook#7]
![image](https://user-images.githubusercontent.com/12979345/136080679-30229f60-a76e-4fe8-b28c-65a476d3ef2c.png)

**Comment by cmoog** [comment]
Ah, good catch. I'll add a boolean option for SSL in the connection setup flow. Will release `v0.2` once that merges.

**Comment by cmoog** [comment]
Upon further inspection, it appears some drivers expose additional SSL configuration that would significantly bloat the prompt-based connection configuration flow. Even though it's tempting, I'm trying to avoid requiring a yaml configuration on the filesystem. I've also ruled out using the extension settings to configure connections as that wouldn't be an appropriate usage and would complicate secret storage. Sadly, vscode virtual file are read-only so that won't work either.

@ryan-efendy any thoughts on how this should be supported?

**Comment by navimondo** [comment]
Charlie and contributors: keep up the great work 😉
Finally I have an SQL scratchbook that I can share with the colleagues and store in the version control.
This issue is a little bit different but similar to the SSL settings, so I am adding it as a comment. 
The Azure SQL connection requires the **"encrypt"** flag to be set to True. I could not find a way to tell the SQL Notebook connection manager to enforce the "encrypt" flag. This results in following error:` Error running command sqlnotebook.connect: Server requires encryption, set 'encrypt' config option to true.. This is likely caused by the extension that contributes sqlnotebook.connect.`
Hopefully there is an easy way to add `Encrypt=True` to the connection string

**Comment by cmoog** [comment]
Thanks @navimondo! Glad you're finding it useful.

I'm working on abstracting the configuration webview form to generic driver configurations so we can solve this problem categorically for all drivers and all configuration options in a clean way. In `v0.3.0`, you'll have the ability to set `encrypt: true` through a checkbox when creating new connections.

**Comment by navimondo** [comment]
Implemented a quick and dirty workaround by editing the "driver.js" file
`...\.vscode\extensions\cmoog.sqlnotebook-0.2.0\out\extension\driver.js`
By changing the encrypt argument to true the driver connects 😮
![SQL Notebook - AzureSQL](https://user-images.githubusercontent.com/30161102/146251521-7249e8e1-21bc-45ee-a944-0dbfa389204f.jpg)
Thanks for giving us an easy to customize database status dashboard.

**Comment by cmoog** [comment]
The configuration option for `mssql` is now available in v0.3.0. I've opened a follow-up issue for the remaining drivers #14
